package com.afis.entity.automodel;

import java.util.Date;

public class Operator {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SN_OPERATOR.ID
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SN_OPERATOR.LOGIN_ACCOUNT
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    private String loginAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SN_OPERATOR.ACCOUNT_NAME
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SN_OPERATOR.PASSWORD
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SN_OPERATOR.MOBILE
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SN_OPERATOR.CLIENT_TYPE
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    private String clientType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SN_OPERATOR.STATUS
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SN_OPERATOR.REMARK
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SN_OPERATOR.LAST_LOGIN_TIME
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    private Date lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SN_OPERATOR.LAST_LOGIN_IP
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    private String lastLoginIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SN_OPERATOR.ID
     *
     * @return the value of T_SN_OPERATOR.ID
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SN_OPERATOR.ID
     *
     * @param id the value for T_SN_OPERATOR.ID
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SN_OPERATOR.LOGIN_ACCOUNT
     *
     * @return the value of T_SN_OPERATOR.LOGIN_ACCOUNT
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public String getLoginAccount() {
        return loginAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SN_OPERATOR.LOGIN_ACCOUNT
     *
     * @param loginAccount the value for T_SN_OPERATOR.LOGIN_ACCOUNT
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public void setLoginAccount(String loginAccount) {
        this.loginAccount = loginAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SN_OPERATOR.ACCOUNT_NAME
     *
     * @return the value of T_SN_OPERATOR.ACCOUNT_NAME
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SN_OPERATOR.ACCOUNT_NAME
     *
     * @param accountName the value for T_SN_OPERATOR.ACCOUNT_NAME
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SN_OPERATOR.PASSWORD
     *
     * @return the value of T_SN_OPERATOR.PASSWORD
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SN_OPERATOR.PASSWORD
     *
     * @param password the value for T_SN_OPERATOR.PASSWORD
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SN_OPERATOR.MOBILE
     *
     * @return the value of T_SN_OPERATOR.MOBILE
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SN_OPERATOR.MOBILE
     *
     * @param mobile the value for T_SN_OPERATOR.MOBILE
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SN_OPERATOR.CLIENT_TYPE
     *
     * @return the value of T_SN_OPERATOR.CLIENT_TYPE
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public String getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SN_OPERATOR.CLIENT_TYPE
     *
     * @param clientType the value for T_SN_OPERATOR.CLIENT_TYPE
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public void setClientType(String clientType) {
        this.clientType = clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SN_OPERATOR.STATUS
     *
     * @return the value of T_SN_OPERATOR.STATUS
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SN_OPERATOR.STATUS
     *
     * @param status the value for T_SN_OPERATOR.STATUS
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SN_OPERATOR.REMARK
     *
     * @return the value of T_SN_OPERATOR.REMARK
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SN_OPERATOR.REMARK
     *
     * @param remark the value for T_SN_OPERATOR.REMARK
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SN_OPERATOR.LAST_LOGIN_TIME
     *
     * @return the value of T_SN_OPERATOR.LAST_LOGIN_TIME
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SN_OPERATOR.LAST_LOGIN_TIME
     *
     * @param lastLoginTime the value for T_SN_OPERATOR.LAST_LOGIN_TIME
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SN_OPERATOR.LAST_LOGIN_IP
     *
     * @return the value of T_SN_OPERATOR.LAST_LOGIN_IP
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SN_OPERATOR.LAST_LOGIN_IP
     *
     * @param lastLoginIp the value for T_SN_OPERATOR.LAST_LOGIN_IP
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_OPERATOR
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", loginAccount=").append(loginAccount);
        sb.append(", accountName=").append(accountName);
        sb.append(", password=").append(password);
        sb.append(", mobile=").append(mobile);
        sb.append(", clientType=").append(clientType);
        sb.append(", status=").append(status);
        sb.append(", remark=").append(remark);
        sb.append(", lastLoginTime=").append(lastLoginTime);
        sb.append(", lastLoginIp=").append(lastLoginIp);
        sb.append("]");
        return sb.toString();
    }
}