package com.afis.entity.automodel;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SN_ROLE.ID
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SN_ROLE.ROLE_NAME
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SN_ROLE.CLIENT_TYPE
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    private String clientType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SN_ROLE.REMARK
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SN_ROLE.ID
     *
     * @return the value of T_SN_ROLE.ID
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SN_ROLE.ID
     *
     * @param id the value for T_SN_ROLE.ID
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SN_ROLE.ROLE_NAME
     *
     * @return the value of T_SN_ROLE.ROLE_NAME
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SN_ROLE.ROLE_NAME
     *
     * @param roleName the value for T_SN_ROLE.ROLE_NAME
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SN_ROLE.CLIENT_TYPE
     *
     * @return the value of T_SN_ROLE.CLIENT_TYPE
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public String getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SN_ROLE.CLIENT_TYPE
     *
     * @param clientType the value for T_SN_ROLE.CLIENT_TYPE
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public void setClientType(String clientType) {
        this.clientType = clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SN_ROLE.REMARK
     *
     * @return the value of T_SN_ROLE.REMARK
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SN_ROLE.REMARK
     *
     * @param remark the value for T_SN_ROLE.REMARK
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_ROLE
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roleName=").append(roleName);
        sb.append(", clientType=").append(clientType);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }
}