package com.afis.entity.automodel;

public class RolePermissionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SN_ROLE_PERMISSION.ROLE_ID
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SN_ROLE_PERMISSION.MENU_ID
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    private Long menuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SN_ROLE_PERMISSION.ROLE_ID
     *
     * @return the value of T_SN_ROLE_PERMISSION.ROLE_ID
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SN_ROLE_PERMISSION.ROLE_ID
     *
     * @param roleId the value for T_SN_ROLE_PERMISSION.ROLE_ID
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SN_ROLE_PERMISSION.MENU_ID
     *
     * @return the value of T_SN_ROLE_PERMISSION.MENU_ID
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SN_ROLE_PERMISSION.MENU_ID
     *
     * @param menuId the value for T_SN_ROLE_PERMISSION.MENU_ID
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_ROLE_PERMISSION
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleId=").append(roleId);
        sb.append(", menuId=").append(menuId);
        sb.append("]");
        return sb.toString();
    }
}