package com.afis.entity.automodel;

import java.util.Date;

public class RolePermission extends RolePermissionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SN_ROLE_PERMISSION.BIND_TIME
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    private Date bindTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SN_ROLE_PERMISSION.BIND_TIME
     *
     * @return the value of T_SN_ROLE_PERMISSION.BIND_TIME
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public Date getBindTime() {
        return bindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SN_ROLE_PERMISSION.BIND_TIME
     *
     * @param bindTime the value for T_SN_ROLE_PERMISSION.BIND_TIME
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    public void setBindTime(Date bindTime) {
        this.bindTime = bindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_ROLE_PERMISSION
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bindTime=").append(bindTime);
        sb.append("]");
        return sb.toString();
    }
}