package com.afis.entity.autodao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.afis.entity.automodel.Menu;
import com.afis.entity.automodel.MenuExample;

@Mapper
public interface MenuMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_SN_MENU
	 *
	 * @mbg.generated Fri Jul 14 14:58:26 CST 2017
	 */
	long countByExample(MenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_SN_MENU
	 *
	 * @mbg.generated Fri Jul 14 14:58:26 CST 2017
	 */
	int deleteByExample(MenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_SN_MENU
	 *
	 * @mbg.generated Fri Jul 14 14:58:26 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_SN_MENU
	 *
	 * @mbg.generated Fri Jul 14 14:58:26 CST 2017
	 */
	int insert(Menu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_SN_MENU
	 *
	 * @mbg.generated Fri Jul 14 14:58:26 CST 2017
	 */
	int insertSelective(Menu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_SN_MENU
	 *
	 * @mbg.generated Fri Jul 14 14:58:26 CST 2017
	 */
	List<Menu> selectByExampleWithRowbounds(MenuExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_SN_MENU
	 *
	 * @mbg.generated Fri Jul 14 14:58:26 CST 2017
	 */
	List<Menu> selectByExample(MenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_SN_MENU
	 *
	 * @mbg.generated Fri Jul 14 14:58:26 CST 2017
	 */
	Menu selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_SN_MENU
	 *
	 * @mbg.generated Fri Jul 14 14:58:26 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Menu record, @Param("example") MenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_SN_MENU
	 *
	 * @mbg.generated Fri Jul 14 14:58:26 CST 2017
	 */
	int updateByExample(@Param("record") Menu record, @Param("example") MenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_SN_MENU
	 *
	 * @mbg.generated Fri Jul 14 14:58:26 CST 2017
	 */
	int updateByPrimaryKeySelective(Menu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_SN_MENU
	 *
	 * @mbg.generated Fri Jul 14 14:58:26 CST 2017
	 */
	int updateByPrimaryKey(Menu record);
}