package com.afis.entity.autodao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.afis.entity.automodel.Operator;
import com.afis.entity.automodel.OperatorExample;
@Mapper
public interface OperatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_OPERATOR
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    long countByExample(OperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_OPERATOR
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    int deleteByExample(OperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_OPERATOR
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_OPERATOR
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    int insert(Operator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_OPERATOR
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    int insertSelective(Operator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_OPERATOR
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    List<Operator> selectByExampleWithRowbounds(OperatorExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_OPERATOR
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    List<Operator> selectByExample(OperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_OPERATOR
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    Operator selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_OPERATOR
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    int updateByExampleSelective(@Param("record") Operator record, @Param("example") OperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_OPERATOR
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    int updateByExample(@Param("record") Operator record, @Param("example") OperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_OPERATOR
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    int updateByPrimaryKeySelective(Operator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_OPERATOR
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    int updateByPrimaryKey(Operator record);
}