package com.afis.entity.autodao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.afis.entity.automodel.Role;
import com.afis.entity.automodel.RoleExample;
@Mapper
public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_ROLE
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    long countByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_ROLE
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    int deleteByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_ROLE
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_ROLE
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_ROLE
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_ROLE
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    List<Role> selectByExampleWithRowbounds(RoleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_ROLE
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    List<Role> selectByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_ROLE
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    Role selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_ROLE
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    int updateByExampleSelective(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_ROLE
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    int updateByExample(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_ROLE
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_ROLE
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    int updateByPrimaryKey(Role record);
}