package com.afis.entity.autodao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.afis.entity.automodel.RolePermission;
import com.afis.entity.automodel.RolePermissionExample;
import com.afis.entity.automodel.RolePermissionKey;
@Mapper
public interface RolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_ROLE_PERMISSION
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    long countByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_ROLE_PERMISSION
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    int deleteByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_ROLE_PERMISSION
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    int deleteByPrimaryKey(RolePermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_ROLE_PERMISSION
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    int insert(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_ROLE_PERMISSION
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    int insertSelective(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_ROLE_PERMISSION
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    List<RolePermission> selectByExampleWithRowbounds(RolePermissionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_ROLE_PERMISSION
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    List<RolePermission> selectByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_ROLE_PERMISSION
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    RolePermission selectByPrimaryKey(RolePermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_ROLE_PERMISSION
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    int updateByExampleSelective(@Param("record") RolePermission record, @Param("example") RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_ROLE_PERMISSION
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    int updateByExample(@Param("record") RolePermission record, @Param("example") RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_ROLE_PERMISSION
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    int updateByPrimaryKeySelective(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SN_ROLE_PERMISSION
     *
     * @mbg.generated Fri Jul 14 14:58:26 CST 2017
     */
    int updateByPrimaryKey(RolePermission record);
}